name: Test

on:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/test.yml'
    - 'poc/**'
  pull_request:
    paths:
    - '.github/workflows/test.yml'
    - 'poc/**'

jobs:
  test:
    name: "Run unit tests for reference code"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: pip

    - name: Install dependencies
      working-directory: poc
      run: python -m pip install -r requirements.txt

    - name: Run tests
      working-directory: poc
      run: python -m unittest

    - name: Enforce type hints
      working-directory: poc
      run: python -m mypy *.py tests/*.py

    - name: Run examples
      working-directory: poc
      run: python examples.py
